const exampleUsers = {
    test1: [
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
        { name: 'Code Review', isDone: false },
        { name: 'Yoga', isDone: true },
        { name: 'Fix bugs', isDone: false },
    ]
}

class LocalStorage {
    constructor() {
        this.usersTodos = exampleUsers;
    }

    getItem(key) {
        if (this.usersTodos[key]) {
            return this.usersTodos[key];
        }
        return null;
    }

    setItem(key, value) {
        this.usersTodos[key] = value;
    }

    removeItem(key) {
        delete this.usersTodos[key];
    }
};

module.exports = { LocalStorage };
